// <auto-generated />
namespace project3_backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class listnamenotnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listnamenotnull));
        
        string IMigrationMetadata.Id
        {
            get { return "201808021722188_list-name-not-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
