// <auto-generated />
namespace project3_backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class listitemselection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listitemselection));
        
        string IMigrationMetadata.Id
        {
            get { return "201808231603519_list item selection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
